name: 'aws sqs github action'
description: 'Sends a message when the action is triggered with the github context.'
inputs:
  region:
    description: 'aws region'
  accessKeyId:
    description: 'aws access key'
  secretAccessKey:
    description: 'aws secret key'
  queueUrl:
    description: 'aws sqs queue url'

runs:
  using: 'node12'
  main: 'index.js'
